### ISSUE TITLE
FindEigen.cmake package name different from upstream

### ISSUE THREAD

**Issue by traversaro** [ros/cmake_modules#25]
The `FindEigen.cmake` distributed in this repository uses `Eigen` as a package name, and it populates the `EIGEN_INCLUDE_DIR` and `EIGEN_INCLUDE_DIRS` variable. 
However the official Find module [1] and the Config file [2] distributed with Eigen uses `Eigen3` as a package name, and they populate the `EIGEN3_INCLUDE_DIR` variable. 
There is any reason to use a package name different from upstream in `ros/cmake_modules`?

[1] : https://bitbucket.org/eigen/eigen/src/167ce78594dc4e7a4b9ca27fc745e674300e85ff/cmake/FindEigen3.cmake?at=default
[2] : https://bitbucket.org/eigen/eigen/src/167ce78594dc4e7a4b9ca27fc745e674300e85ff/cmake/Eigen3Config.cmake.in?at=default

**Comment by wjwwood** [comment]
I'm not sure, maybe so that it does not conflict. This module was originally introduce (at the time in `catkin`) because `Eigen` did not distribute a CMake Module. If `Eigen`'s existing CMake Module works for our packages then we could eventually phase out this Module in our package.

**Comment by traversaro** [comment]
`FindEigen3.cmake` is shipping with Eigen in Trusty [1] but apparently not in Precise [2].
I just found this comment by @adolfo-rt from when `FindEigen.cmake` was added do `cmake_modules` : https://github.com/ros/cmake_modules/pull/11#issuecomment-34045257 . Since those comment was made, a couple things changed:
- Trusty was released, shipping an Eigen version which install its own `FindEigen3.cmake` that exports `EIGEN3_*` variables. 
- The `Eigen3Config.cmake` file shipping with Eigen default branch was fixed in [3] and now exports `EIGEN3_*` variables, consistently with the `FindEigen3.cmake` shipped with Eigen.

[1] http://packages.ubuntu.com/trusty/all/libeigen3-dev/filelist
[2] http://packages.ubuntu.com/precise/all/libeigen3-dev/filelist
[3] https://bitbucket.org/eigen/eigen/history-node/167ce78594dc/cmake/Eigen3Config.cmake.in?at=default

**Comment by wjwwood** [comment]
Ok, well this package still supports hydro, so we need to support precise as well. In the future we can remove the Eigen module from this package, but not until either hydro is end-of-life'ed or until we branch this package into an indigo+ specific branch.

**Comment by dirk-thomas** [comment]
The questions is is the FindEigen3,cmake also available in Saucy. Because if not Indigo can't use it anyway.

**Comment by traversaro** [comment]
Apparently the upstream `FindEigen3.cmake` is not installed in Saucy. There is a possible solution to align `cmake_modules` with the Eigen upstream cmake policy: to ship both `FindEigen.cmake` for current ROS modules using Eigen via `find_package(Eigen)` and the upstream `FindEigen3.cmake` for users that choose the upstream cmake policy `find_package(Eigen3)`. 
The latter has the advantage of automatically switching to use `Eigen3Config.cmake` module as soon it starts to be shipped with Eigen Ubuntu packages, and to increase multiplatform compatibility.

**Comment by wjwwood** [comment]
I don't think it is a good idea to duplicate the `FindEigen3.cmake` module here, but I would be ok with some sort of shim which uses the `FindEigen3.cmake` if provided by Eigen, else the `FindEigen.cmake` in this package.

I'm not entirely sure what that shim would look like, but I would consider a pull request with something to that effect. In the mean time I think packages can do something like this:

```
find_package(Eigen3)
if(NOT EIGEN3_FOUND)
  # Fallback to cmake_modules
  find_package(Eigen REQUIRED)
  set(EIGEN3_INCLUDE_DIRS ${EIGEN_INCLUDE_DIRS})
  set(EIGEN3_LIBRARIES ${EIGEN_LIBRARIES})
  # ...
endif()
```

Maybe this can be captured in a macro provided by this package.

**Comment by dirk-thomas** [comment]
At least in Jade the custom module should also warn about the usage and ask users to use the official Eigen3 module instead.

**Comment by wjwwood** [comment]
As of what version of Eigen was this Config file distributed?

I have Eigen 3.2.2 on OS X and there is no CMake Module or Config that I can find.

**Comment by wjwwood** [comment]
Never the less I have created a pull request for inclusion into Jade: https://github.com/ros/cmake_modules/pull/29

**Comment by wjwwood** [comment]
Seems like an issue with Homebrew's packaging, I opened an issue: https://github.com/Homebrew/homebrew/issues/35225

**Comment by wjwwood** [comment]
And... it's fixed in Homebrew, I'll merge the pull request with @dirk-thomas's comments and release version with the deprecation message into Jade.

One step further would be to collect all the packages which `find_package` Eigen and poke their maintainers to update them to use the Eigen provided CMake module for Jade.

**Comment by wjwwood** [comment]
I updated the Jade migration guide and sent a notification to ros-user:

http://lists.ros.org/pipermail/ros-users/2015-July/069526.html

**Comment by de-vri-es** [comment]
Note that Eigen is **not** shipping `FindEigen3.cmake`. Some distributions have decided to install `FindEigen3.cmake` into the global cmake module path, but Eigen itself is not installing it. [1]

Starting with 3.3 eigen will ship an `Eigen3Config.cmake` which will also allow `find_package(Eigen3)` to work. In the mean time, relying on a packagers choice to install certain files manually (which in this case they shouldn't be doing, really) is not very portable.

So I don't think that relying on a system wide `FindEigen3.cmake` is a good solution.

[1] http://eigen.tuxfamily.org/bz/show_bug.cgi?id=1219

**Comment by wjwwood** [comment]
It's in Ubuntu and Homebrew (which is what the majority of our users use, but obviously not what everyone uses), and for now the cmake_modules one will be available as a backup for other platforms, but having a Module in this package is not a long term solution either.

Eigen maintainers should push on getting their `EigenConfig.cmake` back ported if possible if they believe that to be the right solution. This whole issue exists because Eigen hasn't been distributing the right files and won't be until 3.3, according to your research.

So, I think there's nothing we need to change at the moment. On platforms which distribute the Module, packages can use that, and on platforms that do not, they can use this package's Module. In the distant future all platforms will either have the Module or the Config file and this package's Module can be removed then.

**Comment by de-vri-es** [comment]
Right, it is unfortunate though that the recommendation now is to use `find_package(Eigen3)` without fallback to the `FindEigen.cmake` provided here.

That being said, Arch Linux decided to be pragmatic and backported the `Eigen3Config.cmake` into their package. I think Gentoo did something similar. The current situation is still not very neat, but for me personally the issue has been fixed (by the Arch packager).

**Comment by wjwwood** [comment]
The Jade migration page still says you can fallback:

http://wiki.ros.org/jade/Migration#Eigen_CMake_Module_in_cmake_modules

And I did not fork this package for Kinetic, so it will remain as a fallback for now.
